IMAGE PARAMS:
  pooling_class: "icosahedron"
  n_pixels: 12288
  depth: 3
  laplacian_type: "combinatorial"

MODEL PARAMS:
  conv1_input_channels: 3
  conv1_output_channels: 32
  conv1_kernel_size: 7
  bottleneck_layer_input_channels: [32,64,96]
  bottleneck_layer1_kernel_size: 1
  bottleneck_layer_output_channels: [64,96]
  bottleneck_layer2_kernel_size: 3
  bottleneck_layer2_output_channels: 96
  bottleneck_layer3_kernel_size: 1
  bottleneck_layer_stride: [1,2,2]
  conv2_input_channels: 96
  conv2_kernel_size: 3
  conv2_output_channels: 3
  norm_fn: "batch"
  partition: [0.7,0.2,0.1]
  batch_size: 64
  learning_rate: 0.001
  n_epochs: 30
  

SAVING:
  path_to_data: "/data/climate/data_5_all"
  tensorboard_path: "./"
  model_save_path: "./"

DATALOADERS:
  download: False
  means_path: means.npy
  stds_path: stds.npy
  seed: 1

REDUCEONPLATEAU:
  reducelronplateau_mode: "min"
  reducelronplateau_factor: 0.05
  reducelronplateau_patience: 3
STEP:
  steplr_step_size: 30
  steplr_gamma: 0.1

WARMUP:
  warmuplr_warmup_start_value: 0.001
  warmuplr_warmup_end_value: 0.001
  warmuplr_warmup_duration: 1

EARLY_STOPPING:
  earlystopping_patience: 30
  

